"""empty message

Revision ID: e03d9d2fe26e
Revises: None
Create Date: 2016-11-14 14:20:33.879807

"""

# revision identifiers, used by Alembic.
revision = 'e03d9d2fe26e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tools', sa.Column('quick_description', sa.String(length=256), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tools', 'quick_description')
    ### end Alembic commands ###
